### ISSUE TITLE
various react-universal component examples are throwing errors using react-leaflet-universal in Razzle SSR app

### ISSUE THREAD

**Issue by laurencefass** [masotime/react-leaflet-universal#21]
ive been trying to use react-leaflet-universal in a razzle.js SSR app and quite a lot of the examples from the react-leaflet repo are failing with a variety of errors. I have tested the same components with vanilla React CRA app and they work ok.

Components being tested:
https://github.com/PaulLeCam/react-leaflet/tree/master/example/components

### Expected behavior

1. All the example components from main repo should work using following package.json spec:

```
    "express": "^4.17.1",
    "leaflet": "^1.6.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-leaflet": "^2.6.1",
    "react-leaflet-universal": "^2.1.0",
    "react-router-dom": "^5.0.1"
```  

### Actual behavior

I'm systematically testing all the examples in my test app and im logging the components that don't immediately work with react-leaflet-universal but work fine with react-leaflet in a React SPA.

Following examples are broken showing errors below:

DRAG AND DROP
https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/draggable-marker.js

result: 
```
TypeError: Cannot read property 'getLatLng' of undefined
NewClass.DraggableExample.updatePosition
src/Draggable.tsx:42
  39 |   const marker = this.refmarker.current
  40 |   if (marker != null) {
  41 |     this.setState({
> 42 |       marker: marker.leafletElement.getLatLng(),
     | ^  43 |     })
  44 |   }
  45 | }
```

EVENTS HANDLING
https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/events.js

result: clicking anywhere on the map results white screen and error:
```
Uncaught TypeError: Cannot read property 'locate' of undefined
    at NewClass.EventsExample.handleClick (Events.tsx:28)
    at NewClass.fire (leaflet-src.js:593)
    at NewClass._fireDOMEvent (leaflet-src.js:4452)
    at NewClass._handleDOMEvent (leaflet-src.js:4409)
    at HTMLDivElement.handler (leaflet-src.js:2679)
```
LAYERS CONTROL
https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/layers-control.js

SVG OVERLAY
https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/svg-overlay.js

both are giving similar error reports:
```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `BrokenExample`.
    in BrokenExample (created by Home)
    in div (created by Home)
    in Home (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in App
    in Router (created by BrowserRouter)
    in BrowserRouter
console.<computed> @ index.js:1
warningWithoutStack @ react.development.js:167
warning @ react.development.js:638
createElementWithValidation @ react.development.js:2035
render @ LayersControl.tsx:31
finishClassComponent @ react-dom.development.js:18470
updateClassComponent @ react-dom.development.js:18423
beginWork$1 @ react-dom.development.js:20186
beginWork$$1 @ react-dom.development.js:25756
performUnitOfWork @ react-dom.development.js:24695
workLoopSync @ react-dom.development.js:24671
performSyncWorkOnRoot @ react-dom.development.js:24270
scheduleUpdateOnFiber @ react-dom.development.js:23698
updateContainer @ react-dom.development.js:27103
(anonymous) @ react-dom.development.js:27528
unbatchedUpdates @ react-dom.development.js:24433
legacyRenderSubtreeIntoContainer @ react-dom.development.js:27527
hydrate @ react-dom.development.js:27591
./src/client.tsx @ client.tsx:4
__webpack_require__ @ bootstrap:725
fn @ bootstrap:100
1 @ react.svg:1
__webpack_require__ @ bootstrap:725
(anonymous) @ bootstrap:792
(anonymous) @ bootstrap:792
index.js:1 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

```

WSM TILE LAYER
https://github.com/PaulLeCam/react-leaflet/blob/master/example/components/wms-tile-layer.js#L27

result: 
```
GET https://demo.boundlessgeo.com/geoserver/ows?service=WMS&request=GetMap&layers=nasa%3Abluemarble&styles=&format=image%2Fjpeg&transparent=false&version=1.1.1&children=undefined&width=256&height=256&srs=EPSG%3A3857&bbox=0,7514065.628545967,1252344.2714243277,8766409.899970293 net::ERR_CONNECTION_TIMED_OUT
```

Is there a repo of elements tested and confirmed working with "react-leaflet-universal"?

thanks

**Comment by masotime** [comment]
@laurencefass can you try changing `ref` to `leafletRef` in the examples above? I think that should fix the problem.

**Comment by masotime** [comment]
See https://github.com/masotime-sandboxes/next-rlu-example/blob/master/pages/draggable.js for an example of `leafletRef` usage.

**Comment by masotime** [comment]
I've updated React leaflet universal to smartly "proxy" `ref` when it can, so the example now uses `ref` instead of `leafletRef` (you can see the commit history) but if that still fails `leafletRef` should be the way to go.

**Comment by laurencefass** [comment]
thats great news i will try it see how it goes. thanks.

**Comment by masotime** [comment]
Closing for now. Feel free to re-open as needed.
