### ISSUE TITLE
[ error ] ./node_modules/react-leaflet-universal/dist/decorator.js

### ISSUE THREAD

**Issue by gromchen** [masotime/react-leaflet-universal#23]
Please test `react-leaflet-universal` with the new version of next.js
```
"next": "9.3.4"
```
There is an error during compilation
```
[ error ] ./node_modules/react-leaflet-universal/dist/decorator.js
Module not found: Can't resolve 'babel-runtime/core-js/object/get-prototype-of' in '/Users/gromchen/Desktop/gitlab/zakaz-stores-web/node_modules/react-leaflet-universal/dist'
```

**Comment by masotime** [comment]
Hey, I can't reproduce the issue you're seeing here. Clone this repository and try it out - https://github.com/masotime-sandboxes/next-rlu-example/tree/master - works for me.

Can you fork that repository to demonstrate the issue you're seeing?

**Comment by gromchen** [comment]
@masotime 
Thank you for your response, it works with your setup, I used the same versions.
Now, I'm fixing tests and it looks like `ZoomControl` is not exported from `react-leaflet-universal`

**Comment by gromchen** [comment]
Please take a look https://github.com/masotime/react-leaflet-universal/pull/25

**Comment by masotime** [comment]
Approved.... please update to 2.2.1 to get the changes.

**Comment by gromchen** [comment]
It works. Thank you very much
