### ISSUE TITLE
How can I get an object leafletlement?

### ISSUE THREAD

**Issue by chilander1** [masotime/react-leaflet-universal#5]
Hello! Could you give a simple example of how can I get an object leafletlement?
I can not understand how to do this.
Thanks!

**Comment by masotime** [comment]
Hi @chilander1 ,

This is a little tricky, and could definitely be improved. This should work:

```
class Something extends Component {
  leafletRefAvailable(ref) {
    // at this point, this.leafletRef is populated
    console.log(ref.leafletElement);
  }

  render() {
    return (<Map leafletRef={ref => leafletRefAvailable(ref)}></Map>);
  }
}

```

This isn't ideal - but from my testing `componentDidMount()` doesn't have the ref available yet (a bit strange). This workaround should work, but I'll need to work on improving the integration with the React lifecycle.

**Comment by masotime** [comment]
@chilander1 - do you need require help and/or does the above code work? If so, let me know so I can close the issue or take other action. Thanks!

**Comment by masotime** [comment]
Closed due to lack of response / activity.
